### PR TITLE
feature/AOAF-347-add-cookies-banner

### PR DESCRIPTION
**Pull request by wdhda-ch**
Enable cookie banner again.
Have english and welsh wording on the cookie banner.
single test to see if it present on page

### CODE REVIEW

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Review by okoye-companieshouse — APPROVED** [review]

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Pull request merged**
